[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mtlpy_templater"
dynamic = ["description", "version"]

[project.scripts]
mtlpy_templater = "mtlpy_templater:main"
