[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mtlpy_templater"
dynamic = ["description", "version"]
classifiers = ["Private :: Do Not Upload"]

[project.scripts]
mp-templater = "mtlpy_templater.mtlpy_templater:main"
